import pandas as pd
from io import BytesIO
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side

def _apply_standard_header(writer, report_type: str):
    yellow_fill = PatternFill(start_color="F4B000", end_color="F4B000", fill_type="solid")
    light_yellow_fill = PatternFill(start_color="FFF2CC", end_color="FFF2CC", fill_type="solid")
    light_blue_fill = PatternFill(start_color="B4C6E7", end_color="B4C6E7", fill_type="solid")
    dark_blue_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    
    bold_font = Font(bold=True)
    white_bold_font = Font(color="FFFFFF", bold=True)
    green_bold_font = Font(color="00B050", bold=True)
    
    for sheet_name in writer.sheets:
        ws = writer.sheets[sheet_name]
        
        # Row 2: Main Title
        ws.merge_cells('A2:K3')
        cell = ws['A2']
        cell.value = "Report Generated By ProAnalyser.in"
        cell.font = Font(size=14, bold=True)
        cell.fill = yellow_fill
        cell.alignment = Alignment(horizontal="left", vertical="center")
        
        if report_type == "GST":
            # GST specific meta info
            ws.merge_cells('A5:K5')
            ws['A5'] = "GST ANALYSIS REPORT (1)"
            ws['A5'].fill = light_yellow_fill
            
            ws.merge_cells('A6:K6')
            ws['A6'].fill = light_yellow_fill
            
            ws.merge_cells('A7:K7')
            ws['A7'] = "GSTIN             - 27AADCB2230M1Z2"
            ws['A7'].fill = light_yellow_fill
            
            ws.merge_cells('A8:K8')
            ws['A8'] = "Legal Name        - Jiguna Tech Private Limited"
            ws['A8'].fill = light_yellow_fill
        else:
            # Row 4: Accuracy statement
            ws['A4'] = f"Accuracy : 100%. All the {report_type} records are verified"
            ws['A4'].font = green_bold_font
            
            # Row 5-7: Meta info
            ws.merge_cells('A5:K5')
            ws['A5'] = f"{report_type.upper()} REPORT (1)"
            ws['A5'].fill = light_yellow_fill
            
            ws.merge_cells('A6:K6')
            ws['A6'].fill = light_yellow_fill
            
            ws.merge_cells('A7:K7')
            ws['A7'] = "Applicant    XXXX XXXX 4821"
            ws['A7'].fill = light_yellow_fill
            
            # Row 9: Sub-title
            ws.merge_cells('A9:D9')
            ws['A9'] = "Uploaded Files & Results"
            ws['A9'].font = bold_font
            ws['A9'].fill = light_blue_fill
        
        # Row 10: Column Headers styling
        for col in range(1, ws.max_column + 1):
            header_cell = ws.cell(row=10, column=col)
            header_cell.fill = dark_blue_fill
            header_cell.font = white_bold_font

def generate_bank_excel(applicant_id: str) -> BytesIO:
    # 1. overview
    overview_data = {"Metric": ["Account Name", "Account Number", "Bank Name", "IFSC", "Period"], "Value": ["Mock User", "1234567890", "HDFC Bank", "HDFC0001234", "01-07-2026 to 31-07-2026"]}
    df_overview = pd.DataFrame(overview_data)
    
    # 2. summary
    summary_data = {"Metric": ["Opening Balance", "Closing Balance", "Total Credit", "Total Debit", "Average Balance"], "Value": ["50000.00", "82557.00", "48945.00", "16388.00", "75000.00"]}
    df_summary = pd.DataFrame(summary_data)
    
    # 3. all txns
    txn_data = {
        "Date": ["01-07-2026", "02-07-2026", "03-07-2026", "05-07-2026", "08-07-2026", "10-07-2026", "12-07-2026", "15-07-2026", "18-07-2026", "22-07-2026", "25-07-2026", "28-07-2026", "31-07-2026"],
        "Description": ["Opening Balance", "Salary Credit", "UPI - Grocery Store", "Electricity Bill", "UPI - Restaurant", "Online Shopping", "Refund Credit", "ATM Withdrawal", "UPI - Fuel Station", "Freelance Payment", "Mobile Recharge", "UPI - Pharmacy", "Interest Credit"],
        "Reference ID": ["OPEN-0701", "SAL-784512", "UPI-123456", "BILL-457821", "UPI-563214", "ECOM-789654", "REF-321478", "ATM-654987", "UPI-112233", "PAY-445566", "MOB-778899", "UPI-998877", "INT-202607"],
        "Debit (INR)": [0, 0, 1250.00, 2340.00, 780.00, 3499.00, 0, 5000.00, 1800.00, 0, 599.00, 1120.00, 0],
        "Credit (INR)": [0, 35000.00, 0, 0, 0, 0, 1200.00, 0, 0, 12500.00, 0, 0, 245.00],
        "Balance (INR)": [50000.00, 85000.00, 83750.00, 81410.00, 80630.00, 77131.00, 78331.00, 73331.00, 71531.00, 84031.00, 83432.00, 82312.00, 82557.00]
    }
    df_all_txns = pd.DataFrame(txn_data)
    
    # 4. Cashflow summary
    cashflow_data = {"Month": ["Jul-2026"], "Total Inflow": [48945.00], "Total Outflow": [16388.00], "Net Cashflow": [32557.00]}
    df_cashflow = pd.DataFrame(cashflow_data)
    
    # 5. chq return txns
    chq_ret_data = {"Date": ["07-07-2026"], "Description": ["Cheque Return - Insufficient Funds"], "Cheque No": ["000123"], "Amount": [5000.00]}
    df_chq_ret = pd.DataFrame(chq_ret_data)
    
    # 6. Red alerts
    red_alerts_data = {"Alert Type": ["Cheque Bounce", "Low Balance"], "Count": [1, 0], "Severity": ["High", "Low"]}
    df_red_alerts = pd.DataFrame(red_alerts_data)
    
    # 7. red alert details
    red_alert_det_data = {"Date": ["07-07-2026"], "Alert Type": ["Cheque Bounce"], "Details": ["Cheque 000123 bounced due to insufficient funds"]}
    df_red_alert_det = pd.DataFrame(red_alert_det_data)
    
    # 8. countery party
    counterparty_data = {"Name": ["Employer Inc", "Grocery Store", "Electricity Board"], "Total Credit": [35000.00, 0, 0], "Total Debit": [0, 1250.00, 2340.00]}
    df_counterparty = pd.DataFrame(counterparty_data)
    
    # 9. recurring credits
    rec_cred_data = {"Description": ["Salary Credit"], "Average Amount": [35000.00], "Frequency": ["Monthly"]}
    df_rec_cred = pd.DataFrame(rec_cred_data)
    
    # 10. recurring debits
    rec_deb_data = {"Description": ["Electricity Bill", "Mobile Recharge"], "Average Amount": [2340.00, 599.00], "Frequency": ["Monthly", "Monthly"]}
    df_rec_deb = pd.DataFrame(rec_deb_data)
    
    # 11. loan
    loan_summary_data = {"Loan Account": ["LOAN-9988"], "Bank": ["SBI"], "EMI Amount": [15000.00], "Status": ["Active"]}
    df_loan_summary = pd.DataFrame(loan_summary_data)
    
    # 12. loan txns
    loan_txns_data = {"Date": ["05-07-2026"], "Description": ["EMI Payment LOAN-9988"], "Amount": [15000.00]}
    df_loan_txns = pd.DataFrame(loan_txns_data)
    
    # 13. EMI txns
    emi_txns_data = {"Date": ["05-07-2026"], "Description": ["EMI Payment LOAN-9988"], "Amount": [15000.00]}
    df_emi_txns = pd.DataFrame(emi_txns_data)
    
    # 14. partywise txns
    party_txns_data = {"Party": ["Employer Inc"], "Date": ["02-07-2026"], "Type": ["Credit"], "Amount": [35000.00]}
    df_party_txns = pd.DataFrame(party_txns_data)
    
    # 15. high value txns
    high_val_txns_data = {"Date": ["02-07-2026", "22-07-2026"], "Description": ["Salary Credit", "Freelance Payment"], "Amount": [35000.00, 12500.00], "Type": ["Credit", "Credit"]}
    df_high_val = pd.DataFrame(high_val_txns_data)
    
    # 16. duplicate txns
    dup_txns_data = {"Date": [], "Description": [], "Amount": [], "Reference ID": []}
    df_dup = pd.DataFrame(dup_txns_data)
    
    # 17. utility txns
    util_txns_data = {"Date": ["05-07-2026", "25-07-2026"], "Description": ["Electricity Bill", "Mobile Recharge"], "Amount": [2340.00, 599.00]}
    df_util = pd.DataFrame(util_txns_data)
    
    # 18. cash and atm txns
    cash_atm_data = {"Date": ["15-07-2026"], "Description": ["ATM Withdrawal"], "Amount": [5000.00], "Type": ["Debit"]}
    df_cash_atm = pd.DataFrame(cash_atm_data)
    
    # 19. chq txns
    chq_txns_data = {"Date": ["07-07-2026"], "Description": ["Cheque Issue"], "Cheque No": ["000124"], "Amount": [2000.00], "Type": ["Debit"]}
    df_chq_txns = pd.DataFrame(chq_txns_data)
    
    # 20. charges txns
    charges_data = {"Date": ["30-07-2026"], "Description": ["SMS Alert Charges"], "Amount": [15.00]}
    df_charges = pd.DataFrame(charges_data)
    
    # 21. salary txns
    salary_txns_data = {"Date": ["02-07-2026"], "Description": ["Salary Credit"], "Amount": [35000.00]}
    df_salary = pd.DataFrame(salary_txns_data)
    
    # 22. monthly summary
    monthly_summary_data = {"Month": ["Jul-2026"], "Total Credit": [48945.00], "Total Debit": [16388.00], "Net": [32557.00]}
    df_monthly_summary = pd.DataFrame(monthly_summary_data)
    
    # 23. daily balance
    daily_balance_data = {"Date": ["01-07-2026", "02-07-2026", "03-07-2026"], "End of Day Balance": [50000.00, 85000.00, 83750.00]}
    df_daily_balance = pd.DataFrame(daily_balance_data)
    
    # 24. categories
    categories_data = {"Category": ["Salary", "Utilities", "Shopping", "Cash"], "Amount": [35000.00, 2939.00, 3499.00, 5000.00]}
    df_categories = pd.DataFrame(categories_data)
    
    # 25. counterparty monthly
    cp_monthly_data = {"Counterparty": ["Employer Inc"], "Month": ["Jul-2026"], "Amount": [35000.00], "Type": ["Credit"]}
    df_cp_monthly = pd.DataFrame(cp_monthly_data)
    
    # 26. recurring and loan txns
    rec_loan_txns_data = {"Date": ["05-07-2026"], "Description": ["EMI Payment LOAN-9988"], "Amount": [15000.00], "Type": ["Loan EMI"]}
    df_rec_loan_txns = pd.DataFrame(rec_loan_txns_data)
    
    # 27. biz cashflow
    biz_cashflow_data = {"Metric": ["Revenue", "Operating Expenses", "Net Cashflow"], "Amount": [35000.00, 16388.00, 18612.00]}
    df_biz_cashflow = pd.DataFrame(biz_cashflow_data)
    
    # 28. counterparty monthly m2
    cp_monthly_m2_data = {"Counterparty": ["Grocery Store"], "Month": ["Jul-2026"], "Amount": [1250.00], "Type": ["Debit"]}
    df_cp_monthly_m2 = pd.DataFrame(cp_monthly_m2_data)
    
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_overview.to_excel(writer, sheet_name='overview', index=False, startrow=9)
        df_summary.to_excel(writer, sheet_name='summary', index=False, startrow=9)
        df_all_txns.to_excel(writer, sheet_name='all txns', index=False, startrow=9)
        df_cashflow.to_excel(writer, sheet_name='Cashflow summary', index=False, startrow=9)
        df_chq_ret.to_excel(writer, sheet_name='chq return txns', index=False, startrow=9)
        df_red_alerts.to_excel(writer, sheet_name='Red alerts', index=False, startrow=9)
        df_red_alert_det.to_excel(writer, sheet_name='red alert details', index=False, startrow=9)
        df_counterparty.to_excel(writer, sheet_name='countery party', index=False, startrow=9)
        df_rec_cred.to_excel(writer, sheet_name='recurring credits', index=False, startrow=9)
        df_rec_deb.to_excel(writer, sheet_name='recurring debits', index=False, startrow=9)
        df_loan_summary.to_excel(writer, sheet_name='loan', index=False, startrow=9)
        df_loan_txns.to_excel(writer, sheet_name='loan txns', index=False, startrow=9)
        df_emi_txns.to_excel(writer, sheet_name='EMI txns', index=False, startrow=9)
        df_party_txns.to_excel(writer, sheet_name='partywise txns', index=False, startrow=9)
        df_high_val.to_excel(writer, sheet_name='high value txns', index=False, startrow=9)
        df_dup.to_excel(writer, sheet_name='duplicate txns', index=False, startrow=9)
        df_util.to_excel(writer, sheet_name='utility txns', index=False, startrow=9)
        df_cash_atm.to_excel(writer, sheet_name='cash and atm txns', index=False, startrow=9)
        df_chq_txns.to_excel(writer, sheet_name='chq txns', index=False, startrow=9)
        df_charges.to_excel(writer, sheet_name='charges txns', index=False, startrow=9)
        df_salary.to_excel(writer, sheet_name='salary txns', index=False, startrow=9)
        
        # New sheets
        df_monthly_summary.to_excel(writer, sheet_name='monthly summary', index=False, startrow=9)
        df_daily_balance.to_excel(writer, sheet_name='daily balance', index=False, startrow=9)
        df_categories.to_excel(writer, sheet_name='categories', index=False, startrow=9)
        df_cp_monthly.to_excel(writer, sheet_name='counterparty monthly', index=False, startrow=9)
        df_rec_loan_txns.to_excel(writer, sheet_name='recurring & loan txns', index=False, startrow=9)
        df_biz_cashflow.to_excel(writer, sheet_name='biz cashflow', index=False, startrow=9)
        df_cp_monthly_m2.to_excel(writer, sheet_name='counterparty monthly m2', index=False, startrow=9)
        
        # 29. repayment capacity
        repayment_capacity_data = {"Metric": ["Average Monthly Income", "Existing EMIs", "Proposed EMI", "Net Disposable Income", "Repayment Status"], "Value": ["48945.00", "15000.00", "10000.00", "23945.00", "Eligible"]}
        df_repayment = pd.DataFrame(repayment_capacity_data)
        df_repayment.to_excel(writer, sheet_name='repayment capacity', index=False, startrow=9)
        
        # Apply standard header styling to all sheets
        _apply_standard_header(writer, "Bank Statement")
    
    output.seek(0)
    return output

def generate_gst_excel(applicant_id: str) -> BytesIO:
    # 1. overview
    overview_data = {"Metric": ["Applicant Name", "GSTIN", "Filing Frequency", "Period"], "Value": ["Mock Business", "27AAAAA0000A1Z5", "Monthly", "Apr 2026 - Sep 2026"]}
    df_overview = pd.DataFrame(overview_data)
    
    # 2. tax and summary breakdown
    tax_summary_data = {
        "Metric": ["Annualized Turnover", "Average Monthly Sales", "ITC Utilization Rate", "Compliance Rate", "Total CGST", "Total SGST", "Total IGST"],
        "Value": ["₹ 60,40,000", "₹ 5,03,333", "40.0%", "100% (6/6)", "₹ 2,71,800", "₹ 2,71,800", "₹ 0"],
        "Status": ["Verified", "Consistent Growth", "Optimal", "On-time", "-", "-", "-"]
    }
    df_tax_summary = pd.DataFrame(tax_summary_data)
    
    # 3. transactions
    txn_data = {
        "Month": ["Apr 2026", "May 2026", "Jun 2026", "Jul 2026", "Aug 2026", "Sep 2026"],
        "Return Type": ["GSTR-3B", "GSTR-3B", "GSTR-3B", "GSTR-3B", "GSTR-3B", "GSTR-3B"],
        "Taxable Turnover (INR)": [450000, 480000, 510000, 495000, 525000, 560000],
        "CGST (INR)": [40500, 43200, 45900, 44550, 47250, 50400],
        "SGST (INR)": [40500, 43200, 45900, 44550, 47250, 50400],
        "IGST (INR)": [0, 0, 0, 0, 0, 0],
        "Total Tax (INR)": [81000, 86400, 91800, 89100, 94500, 100800],
        "ITC Claimed (INR)": [32400, 34560, 36720, 35640, 37800, 40320],
        "Filing Status": ["ON TIME", "ON TIME", "ON TIME", "ON TIME", "ON TIME", "ON TIME"]
    }
    df_txns = pd.DataFrame(txn_data)
    
    # 4. monthly trends
    trends_data = {
        "Month": ["Apr 2026", "May 2026", "Jun 2026", "Jul 2026", "Aug 2026", "Sep 2026"],
        "Turnover Growth (%)": ["-", "+6.67%", "+6.25%", "-2.94%", "+6.06%", "+6.67%"],
        "ITC vs Tax Ratio (%)": ["40.0%", "40.0%", "40.0%", "40.0%", "40.0%", "40.0%"]
    }
    df_trends = pd.DataFrame(trends_data)
    
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_overview.to_excel(writer, sheet_name='overview', index=False, startrow=9)
        df_tax_summary.to_excel(writer, sheet_name='tax and summary breakdown', index=False, startrow=9)
        df_txns.to_excel(writer, sheet_name='transactions', index=False, startrow=9)
        df_trends.to_excel(writer, sheet_name='monthly trends', index=False, startrow=9)
        
        _apply_standard_header(writer, "GST")
    
    output.seek(0)
    return output

def generate_itr_excel(applicant_id: str) -> BytesIO:
    itr_data = {
        "Assessment Year": ["AY 2025-26", "AY 2024-25", "AY 2023-24"],
        "Financial Year": ["FY 2024-25", "FY 2023-24", "FY 2022-23"],
        "Gross Total Income (INR)": [1250000, 1080000, 950000],
        "Chapter VI-A Deductions (INR)": [150000, 150000, 150000],
        "Net Taxable Income (INR)": [1100000, 930000, 800000],
        "Total Tax Paid (INR)": [122408, 98500, 72500],
        "YoY Growth Rate": ["+15.7%", "+13.7%", "-"],
        "Filing Status": ["ON TIME", "ON TIME", "ON TIME"]
    }
    df_itr = pd.DataFrame(itr_data)
    
    summary_data = {
        "Metric": ["3-Year Average Income", "3-Year Income CAGR", "Monthly Net Disposable", "Existing Debt Commitment", "FOIR", "Max Loan Eligibility"],
        "Value": ["₹ 10,93,333", "+14.7%", "₹ 93,966", "₹ 1,80,000", "15.96%", "₹ 45,00,000"],
        "Status": ["Verified", "Strong Growth", "Calculated", "Active", "Excellent (< 50%)", "Approved Limit"]
    }
    df_sum = pd.DataFrame(summary_data)
    
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_itr.to_excel(writer, sheet_name='ITR_Multi_Year_Summary', index=False, startrow=9)
        df_sum.to_excel(writer, sheet_name='Income_Capacity_Assessment', index=False, startrow=9)
        _apply_standard_header(writer, "ITR")
    
    output.seek(0)
    return output

def generate_loan_excel(applicant_id: str) -> BytesIO:
    loan_data = {
        "Lender Institution": ["HDFC Bank Ltd", "State Bank of India"],
        "Loan Type": ["Auto / Car Loan", "Personal Loan"],
        "Sanction Amount (INR)": [450000, 300000],
        "Outstanding Balance (INR)": [275000, 175000],
        "Monthly EMI (INR)": [15000, 8000],
        "Tenure Left (Months)": [21, 26],
        "DPD / Overdue Status": ["0 DPD (Clean)", "0 DPD (Clean)"]
    }
    df_loan = pd.DataFrame(loan_data)
    
    summary_data = {
        "Metric": ["Monthly Verified Income", "Total Existing EMIs", "Current FOIR", "Net Available Cashflow", "CIBIL Bureau Track", "Max Additional Loan"],
        "Value": ["₹ 93,966", "₹ 23,000", "24.47%", "₹ 70,966", "785 (Clean Track)", "₹ 20,00,000"],
        "Status": ["Active", "Active Commitments", "Healthy (< 50%)", "Sufficient Buffer", "Excellent", "Recommended Eligible"]
    }
    df_sum = pd.DataFrame(summary_data)
    
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df_loan.to_excel(writer, sheet_name='Active_Loan_Accounts', index=False, startrow=9)
        df_sum.to_excel(writer, sheet_name='FOIR_Debt_Assessment', index=False, startrow=9)
        _apply_standard_header(writer, "Loan")
    
    output.seek(0)
    return output
